### ISSUE TITLE
Files missing in profundo dir after recent commits

### ISSUE THREAD

**Issue by crypdick** [Vaa3D/vaa3d_tools#4]
As of af416b85e5 there were a bunch of my files in the [profundo module](https://github.com/Vaa3D/vaa3d_tools/tree/af416b85e5de165d26027b426cefde182d44c722/hackathon/profundo/profundo). Then, after @qiangouyang pushed 03d6b743b6 these files [went missing](https://github.com/Vaa3D/vaa3d_tools/tree/03d6b743b66b79b09e2bf13331523f9b2b00b3cf/hackathon/profundo/profundo). Strangely, when I look at 03d6b743b6 it shows 11 changed files, but none of them are mine. Because of this, I don't know how to revert the deletions with git. @gnayuy

**Comment by zhizhoualan** [comment]
Can you check it again to see if all files are restored? Thanks.

Zhi

**Comment by crypdick** [comment]
Yes, thanks! Now I just need to get my local changes back in
